/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false --strict-vars false` (hash: ca240d99be89a60248b7f5c5c402dcac)
declare namespace Cloudflare {
	interface Env {
		REALTIME_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").RealtimeDurableObject>;
		LOGGER_DURABLE_OBJECT: DurableObjectNamespace<import("./src/worker").Logger>;
	}
}
interface Env extends Cloudflare.Env {}
